# Generated by Django 3.2.21 on 2023-11-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrectfrend', '0004_alter_friend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='i_took',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friend',
            name='sec_friend',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
