# Generated by Django 3.2.21 on 2023-11-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrectfrend', '0005_auto_20231114_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='sec_friend',
            field=models.CharField(default=False, max_length=2000),
        ),
    ]
