# Generated by Django 3.2.21 on 2023-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrectfrend', '0006_alter_friend_sec_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrectfriend',
            name='i_took',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
