# Generated by Django 3.2.21 on 2023-11-15 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secrectfrend', '0007_auto_20231115_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrectfriend',
            name='secret_friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secret_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secrectfriend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL),
        ),
    ]
