# Generated by Django 3.2.21 on 2023-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrectfrend', '0009_auto_20231115_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='secrectfriend',
            name='i_took',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secrectfriend',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
